name: quizapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  math_expressions: ^2.0.1
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.6
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.5.0
  firebase_auth: ^4.5.0
  
  google_sign_in: ^5.2.1
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  provider: ^6.1.2
  sqflite: ^2.0.0+4
  http: ^1.2.0
  shared_preferences: ^2.0.12
  get: ^4.6.5
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.10

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
